-- Beguiling Studios service pricing
-- Run this in Supabase -> SQL Editor -> New query -> Run.

create table if not exists public.service_pricing (
  id bigint generated by default as identity primary key,
  code text not null unique,
  service_name text not null,
  category text not null,
  person_type text,
  service_type text,
  unit_price numeric(10,2) not null,
  billing_unit text not null default 'each',
  description text,
  active boolean not null default true,
  sort_order integer not null default 0,
  needs_confirmation boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.service_pricing enable row level security;

drop policy if exists "Public can read active pricing" on public.service_pricing;
create policy "Public can read active pricing"
on public.service_pricing
for select
to anon, authenticated
using (active = true);

insert into public.service_pricing
(code, service_name, category, person_type, service_type, unit_price, billing_unit, description, sort_order, needs_confirmation)
values
('bridal_makeup', 'Beguiling Bridal Makeup', 'bridal', 'bride', 'makeup', 2000.00, 'each',
 'Includes a trial, lashes and a small touch-up kit.', 10, false),

('bridal_makeup_hair', 'Beguiling Bridal Makeup & Hair', 'bridal', 'bride', 'makeup_hair', 4000.00, 'each',
 'Includes makeup & hair trial, false lashes and touch-up bag.', 20, false),

('bridesmaids_1500', 'Beguiling Bridesmaids Service', 'bridal_party', 'bridesmaid', 'makeup_hair', 1500.00, 'each',
 'Source price list text is truncated as "Beguiling Bridesmaids Make...". Confirm exact service wording.', 30, true),

('false_lashes', 'Beguiling False Lashes', 'add_on', null, 'lashes', 150.00, 'each',
 null, 40, false),

('flowergirl_hair', 'Beguiling Flowergirl Hairstyling', 'bridal_party', 'flower_girl', 'hair', 400.00, 'each',
 null, 50, false),

('hair_blow', 'Beguiling Hairstyling - Blow', 'hair', 'guest', 'hair', 450.00, 'each',
 'Source price list label is truncated after "Blow-".', 60, true),

('hair_upstyle', 'Beguiling Hairstyling - Upstyle', 'hair', 'guest', 'hair', 600.00, 'each',
 null, 70, false),

('makeup_650', 'Beguiling Makeup - R650', 'makeup', 'guest', 'makeup', 650.00, 'each',
 'The supplied price list contains two rows named "Beguiling Makeup" at different prices. Confirm which client/person type uses this rate.', 80, true),

('makeup_700', 'Beguiling Makeup - R700', 'makeup', 'guest', 'makeup', 700.00, 'each',
 'The supplied price list contains two rows named "Beguiling Makeup" at different prices. Confirm which client/person type uses this rate.', 90, true),

('wedding_promo_6000', 'Beguiling Makeup & Hair Promo', 'package', 'wedding', 'package', 6000.00, 'package',
 'Wedding promotional package.', 100, false),

('mother_1200', 'Beguiling Mother of the Bride/Groom Service', 'bridal_party', 'mother', 'makeup_hair', 1200.00, 'each',
 'Source price list text is truncated after "Beguiling Mother of the Bri...". Confirm exact service wording.', 110, true),

('travel_per_km', 'Beguiling Travel', 'travel', null, 'travel', 8.00, 'km',
 'Calculated from the studio to the venue and back (distance x 2).', 120, false)
on conflict (code) do update set
  service_name = excluded.service_name,
  category = excluded.category,
  person_type = excluded.person_type,
  service_type = excluded.service_type,
  unit_price = excluded.unit_price,
  billing_unit = excluded.billing_unit,
  description = excluded.description,
  active = excluded.active,
  sort_order = excluded.sort_order,
  needs_confirmation = excluded.needs_confirmation,
  updated_at = now();
